version: '3.3'

volumes:
    logs:
        driver: local
    redis-data:

networks:
    weather-net:

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 80:8080
        networks:
            - weather-net
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    redis:
        image: redis:latest
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
            - weather-net
        volumes:
            - redis-data:/data
